### ISSUE TITLE
Unclear/misleading docs

### ISSUE THREAD

**Issue by exclipy** [stephenplusplus/google-auto-auth#27]
In readme.md:

> This works automatically if:
> 
>     your app runs on Google Compute Engine
>     you are authenticated with the gcloud sdk
>     you have the path to a JSON key file as an environment variable named GOOGLE_APPLICATION_CREDENTIALS

Two issues:
1. It doesn't mention that it also works with Google App Engine.  Can you clarify this and whether this works in a Google Cloud Function or a Kubernetes instance?
2. Can you clarify if all of these conditions need to be met or just one of them?

**Comment by stephenplusplus** [comment]
Thanks for the feedback. For some quick answers:

Yes, it works on App Engine. Instead of "Google Compute Engine", it should say "Google Cloud Platform", which encompasses all Google cloud environments (GAE, GCE, Cloud Functions, Kubernetes)

And, only one of those is required.

Thanks for asking. I'd like to improve the docs-- please feel free to contribute some edits that you would find helpful for others.
